DROP TABLE user_genre_count;
CREATE TABLE user_genre_count(
  user_id INT PRIMARY KEY,
  Comedy INT,
  Game INT,
  Slice_of_Life INT,
  Romance INT,
  Mecha INT,
  Psychological INT,
  Harem INT,
  Shounen_Ai INT,
  Magic INT,
  Sports INT,
  Super_Power INT,
  Kids INT,
  Adventure INT,
  Shounen INT,
  Police INT,
  Military INT,
  Seinen INT,
  Space INT,
  Parody INT,
  Hentai INT,
  Samurai INT,
  Yaoi INT,
  Thriller INT,
  Ecchi INT,
  Supernatural INT,
  School INT,
  Music INT,
  Martial_Arts INT,
  Drama INT,
  Mystery INT,
  Sci_Fi INT,
  Dementia INT,
  Fantasy INT,
  Vampire INT,
  Action INT,
  Shoujo INT,
  Cars INT,
  Josei INT,
  Horror INT,
  Historical INT,
  Demons INT
);