DROP TABLE user_genre_count;
CREATE TABLE user_genre_count(
  user_id INT PRIMARY KEY,
  Comedy INT DEFAULT 0,
  Game INT DEFAULT 0,
  Slice_of_Life INT DEFAULT 0,
  Romance INT DEFAULT 0,
  Mecha INT DEFAULT 0,
  Psychological INT DEFAULT 0,
  Harem INT DEFAULT 0,
  Shounen_Ai INT DEFAULT 0,
  Magic INT DEFAULT 0,
  Sports INT DEFAULT 0,
  Super_Power INT DEFAULT 0,
  Kids INT DEFAULT 0,
  Adventure INT DEFAULT 0,
  Shounen INT DEFAULT 0,
  Police INT DEFAULT 0,
  Military INT DEFAULT 0,
  Seinen INT DEFAULT 0,
  Space INT DEFAULT 0,
  Parody INT DEFAULT 0,
  Hentai INT DEFAULT 0,
  Samurai INT DEFAULT 0,
  Yaoi INT DEFAULT 0,
  Thriller INT DEFAULT 0,
  Ecchi INT DEFAULT 0,
  Supernatural INT DEFAULT 0,
  School INT DEFAULT 0,
  Music INT DEFAULT 0,
  Martial_Arts INT DEFAULT 0,
  Drama INT DEFAULT 0,
  Mystery INT DEFAULT 0,
  Sci_Fi INT DEFAULT 0,
  Dementia INT DEFAULT 0,
  Fantasy INT DEFAULT 0,
  Vampire INT DEFAULT 0,
  Action INT DEFAULT 0,
  Shoujo INT DEFAULT 0,
  Cars INT DEFAULT 0,
  Josei INT DEFAULT 0,
  Horror INT DEFAULT 0,
  Historical INT DEFAULT 0,
  Demons INT DEFAULT 0
);

-- ADDS users to table
INSERT INTO user_genre_count
SELECT DISTINCT user_id from animelist;