CREATE TABLE anime(
  anime_id INT PRIMARY KEY,
  name VARCHAR(100),
  score DECIMAL(4,2),
  genres VARCHAR(200),
  english_name VARCHAR(100),
  japanese_name VARCHAR(100),
  type VARCHAR(20),
  episodes INT,
  aired VARCHAR(40),
  premiered VARCHAR(20),
  producers VARCHAR(100),
  licensors VARCHAR(100),
  studios VARCHAR(100),
  source VARCHAR(20),
  duration VARCHAR(20),
  rating VARCHAR(50),
  ranked INT,
  popularity INT,
  score_10 INT,
  score_9 INT,
  score_8 INT,
  score_7 INT,
  score_6 INT,
  score_5 INT,
  score_4 INT,
  score_3 INT,
  score_2 INT,
  score_1 INT
);